language: php
php:
  - '7.0'

# faster builds on new travis setup not using sudo
sudo: false

# cache composer cache
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
# setup application:
  - |
    cd tests
    codecept build
    cd ..

script:
  - |
    cd tests
    codecept run